#!/bin/bash

ACCOUNT="voormedia"
PROJECT="kd"

LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/$ACCOUNT/$PROJECT/releases/latest)

# The releases are returned in the format {"id":3622206,"tag_name":"hello-1.0.0.11",...}, we have to extract the tag_name.
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

ARTIFACT_URL="https://github.com/$ACCOUNT/$PROJECT/releases/download/$LATEST_VERSION/darwin_amd64_kd"

echo "Updating to version $LATEST_VERSION"

curl -L $ARTIFACT_URL -o ~/.bin/kd && chmod +x ~/.bin/kd
